const express = require('express');
const { getFile } = require('../lib/storage');
const router = express.Router();
const path = require('path');
const { setFlash } = require('../middleware/auth');

// Require authentication for all downloads
router.use((req, res, next) => {
  if (!req.session.user) {
    return res.status(401).send('Unauthorized. Please log in.');
  }
  next();
});

// Serve module content from database (fallback when file is missing)
router.get('/module/:id', async (req, res) => {
  try {
    const { query: dbQuery } = require('../config/db');
    const rows = await dbQuery('SELECT * FROM subject_resources WHERE id = ?', [req.params.id]);
    const resource = rows[0];
    if (!resource) {
      return res.status(404).send(`
        <html><body style="font-family:Inter,sans-serif;display:flex;justify-content:center;align-items:center;height:100vh;background:#f9fafb;">
          <div style="text-align:center;"><h2>Module Not Found</h2><p>This module may have been deleted.</p><a href="javascript:history.back()">Go Back</a></div>
        </body></html>`);
    }

    // Security check: block students from accessing locked admin modules
    const userRole = req.session.user?.role;
    if (userRole === 'student' && resource.module_origin !== 'ai_generated') {
      const { getSubjectAssessmentForStudent } = require('../lib/data');
      const subjectId = resource.subject_id;
      if (subjectId) {
        const subjectAssessments = await getSubjectAssessmentForStudent(req.session.user.id, subjectId);
        const hasAnyTakenAssessment = subjectAssessments.some(a => a.taken_at);
        if (!hasAnyTakenAssessment) {
          return res.status(403).send(`
            <html><body style="font-family:Inter,sans-serif;display:flex;justify-content:center;align-items:center;height:100vh;background:#f9fafb;">
              <div style="text-align:center;">
                <span style="font-size:48px;">🔒</span>
                <h2>Module Locked</h2>
                <p>You need to complete the assessment first before you can access this module.</p>
                <a href="javascript:history.back()" style="color:#1a5632;font-weight:600;">Go Back</a>
              </div>
            </body></html>`);
        }
      }
    }

    // If the stored file is still there, serve it
    if (resource.file_path) {
      const cleaned = resource.file_path.replace(/\\/g, '/');
      const stored = await getFile(cleaned);
      if (stored) {
        const ext = path.extname(cleaned).toLowerCase();
        if (ext === '.pdf') {
          res.setHeader('Content-Type', 'application/pdf');
          res.setHeader('Content-Disposition', 'inline; filename="' + path.basename(cleaned) + '"');
        } else {
          res.type(ext || 'bin');
        }
        return res.send(stored.buffer);
      }
    }

    // File is missing — serve content_text from database
    if (resource.content_text) {
      const isHtmlModule = resource.module_origin === 'ai_generated';
      if (isHtmlModule) {
        // Render the AI module content as a styled HTML page
        const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${resource.title || 'Learning Module'}</title>
  <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"><\/script>
  <style>
    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; line-height: 1.8; color: #333; background: #f9fafb; }
    .header { background: linear-gradient(135deg, #1a5632, #2d8a4e); color: #fff; padding: 30px; border-radius: 12px; margin-bottom: 30px; }
    .header h1 { margin: 0 0 8px; font-size: 24px; }
    .header p { margin: 4px 0; opacity: 0.9; font-size: 14px; }
    .badge { display: inline-block; background: rgba(255,255,255,0.2); padding: 4px 12px; border-radius: 20px; font-size: 12px; margin-top: 8px; }
    .content { background: #fff; padding: 30px; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); font-size: 15px; }
    .content h1, .content h2, .content h3 { color: #1a5632; margin-top: 1.5em; }
    .content code { background: #f0f0f0; padding: 2px 6px; border-radius: 4px; }
    .footer { text-align: center; margin-top: 30px; color: #999; font-size: 12px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>${resource.title || 'AI Generated Module'}</h1>
    ${resource.type_of_module ? '<p><strong>Type:</strong> ' + resource.type_of_module + '</p>' : ''}
    ${resource.difficulty_level ? '<span class="badge">' + resource.difficulty_level + '</span>' : ''}
  </div>
  <div class="content" id="rendered-content"></div>
  <script type="text/markdown" id="raw-markdown">
${resource.content_text}
  <\/script>
  <script>
    document.getElementById('rendered-content').innerHTML = marked.parse(document.getElementById('raw-markdown').textContent);
  <\/script>
  <div class="footer">
    <p>Generated by MindQuest AI Learning System</p>
  </div>
</body>
</html>`;
        res.setHeader('Content-Type', 'text/html');
        return res.send(html);
      }

      // Plain text content (admin-uploaded parsed content)
      const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${resource.title || 'Module Content'}</title>
  <style>
    body { font-family: 'Segoe UI', sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; line-height: 1.8; color: #333; background: #f9fafb; }
    .header { background: linear-gradient(135deg, #1a5632, #2d8a4e); color: #fff; padding: 20px; border-radius: 12px; margin-bottom: 20px; }
    .header h1 { margin: 0; font-size: 22px; }
    .content { background: #fff; padding: 30px; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); white-space: pre-wrap; font-size: 15px; }
    .notice { background: #fff3cd; border: 1px solid #ffc107; padding: 12px 16px; border-radius: 8px; margin-bottom: 16px; font-size: 13px; color: #856404; }
    .footer { text-align: center; margin-top: 20px; color: #999; font-size: 12px; }
  </style>
</head>
<body>
  <div class="header"><h1>${resource.title || 'Module'}</h1></div>
  <div class="notice">📄 The original file is no longer available on the server. Showing the extracted text content below.</div>
  <div class="content">${resource.content_text}</div>
  <div class="footer"><p>MindQuest Tutorial Center</p></div>
</body>
</html>`;
      res.setHeader('Content-Type', 'text/html');
      return res.send(html);
    }

    // No file AND no content_text
    return res.status(404).send(`
      <html><body style="font-family:Inter,sans-serif;display:flex;justify-content:center;align-items:center;height:100vh;background:#f9fafb;">
        <div style="text-align:center;"><h2>File Not Available</h2><p>The original file has been removed from the server and no cached content is available.</p><a href="javascript:history.back()">Go Back</a></div>
      </body></html>`);
  } catch (err) {
    console.error('[Download Module Error]', err);
    res.status(500).send('An error occurred while loading the module.');
  }
});

// Download/view file by path
router.get('/', async (req, res, next) => {
  try {
    const fileUrlPath = req.query.path;
    if (!fileUrlPath) {
      setFlash(req, 'error', 'No file specified.');
      return res.redirect('back');
    }

    const decoded = decodeURIComponent(fileUrlPath);
    const cleaned = decoded.replace(/\.\./g, '').replace(/\\/g, '/');

    if (!cleaned.startsWith('/uploads/')) {
      setFlash(req, 'error', 'Invalid file path.');
      return res.redirect('back');
    }

    const stored = await getFile(cleaned);

    if (!stored) {
      // File is missing — fall back to the cached text held in the database.
      // This mattered even on disk; it matters more now, because a row can
      // outlive its object in remote storage just as easily.
      try {
        const { query: dbQuery } = require('../config/db');
        const rows = await dbQuery('SELECT id, content_text FROM subject_resources WHERE file_path = ?', [cleaned]);
        if (rows.length && rows[0].content_text) {
          return res.redirect(`/download/module/${rows[0].id}`);
        }
      } catch (dbErr) {
        console.error('[Download DB Fallback Error]', dbErr);
      }
      setFlash(req, 'error', 'File not found or has been removed from the server.');
      return res.redirect('back');
    }

    const ext = path.extname(cleaned).toLowerCase();
    const baseName = path.basename(cleaned);

    if (ext === '.html' || ext === '.htm') {
      res.type('html');
      return res.send(stored.buffer);
    }
    if (['.png', '.jpg', '.jpeg', '.gif', '.svg', '.webp'].includes(ext)) {
      res.type(ext);
      return res.send(stored.buffer);
    }
    if (ext === '.pdf') {
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', 'inline; filename="' + baseName + '"');
      return res.send(stored.buffer);
    }

    res.setHeader('Content-Disposition', 'attachment; filename="' + baseName + '"');
    res.type(ext || 'bin');
    return res.send(stored.buffer);
  } catch (err) {
    console.error('[Download Route Error]', err);
    try {
      setFlash(req, 'error', 'An error occurred while accessing the file.');
      res.redirect('back');
    } catch (redirectErr) {
      res.status(500).send('File access error. Please go back and try again.');
    }
  }
});

module.exports = router;
